// Web App Manifest — makes the site installable to the home screen on
// Android + desktop Chrome and gives iOS the metadata it needs to render
// a proper standalone app icon. Next.js serves this file automatically at
// /manifest.webmanifest and injects the corresponding <link> tag when the
// root-layout metadata references `manifest: '/manifest.webmanifest'`.
//
// display: 'standalone' means once installed, the site opens without the
// browser chrome — full-screen, address bar gone, back-swipe still works.
// That's the ergonomic upgrade users actually feel from a "PWA".
//
// theme_color + background_color drive the splash screen and window
// chrome on install. Matching them to the site's #080e1a background makes
// the launch feel native instead of flashing white.
//
// Icons: the SVG at /icon.svg scales to any resolution so it satisfies
// Chrome's installability check on its own. The apple-icon PNG is
// generated by app/apple-icon.tsx and picked up by iOS.

import type { MetadataRoute } from 'next'

export default function manifest(): MetadataRoute.Manifest {
  return {
    name:             'Forex Mastery — AI Trading Platform',
    short_name:       'Forex Mastery',
    description:      'AI-driven forex analysis, live signals, economic calendar, and a full trading course.',
    start_url:        '/',
    id:               '/',
    display:          'standalone',
    orientation:      'portrait',
    background_color: '#080e1a',
    theme_color:      '#080e1a',
    categories:       ['finance', 'education', 'business'],
    icons: [
      {
        src:     '/icon.svg',
        sizes:   'any',
        type:    'image/svg+xml',
        purpose: 'any',
      },
      {
        src:     '/apple-icon',
        sizes:   '180x180',
        type:    'image/png',
        purpose: 'any',
      },
    ],
  }
}
