#!/usr/bin/env node
/**
 * scripts/render-stills.mjs
 * Renders all 8 lesson illustration stills as PNG files using Remotion.
 *
 *   node scripts/render-stills.mjs
 *   node scripts/render-stills.mjs --id=CandlestickAnatomy   # single still
 */

import { bundle } from '@remotion/bundler'
import { renderStill, selectComposition } from '@remotion/renderer'
import { createRequire } from 'module'
import path from 'path'
import fs from 'fs/promises'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, '..')

const STILLS = [
  { id: 'CandlestickAnatomy',       file: 'candlestick-anatomy.png' },
  { id: 'CandleTypes',              file: 'candle-types.png' },
  { id: 'MultiCandlePatterns',      file: 'multi-candle-patterns.png' },
  { id: 'Trends',                   file: 'trends.png' },
  { id: 'HeadAndShoulders',         file: 'head-and-shoulders.png' },
  { id: 'ChartPatterns',            file: 'chart-patterns.png' },
  { id: 'TradeEntry',               file: 'trade-entry.png' },
  { id: 'SupportResistance',        file: 'support-resistance.png' },
  { id: 'CandlestickChart',         file: 'candlestick-chart.png' },
  { id: 'CandleTypesChart',         file: 'candle-types-chart.png' },
  { id: 'MultiCandleChart',         file: 'multi-candle-chart.png' },
  { id: 'TrendsChart',              file: 'trends-chart.png' },
  { id: 'HeadShouldersChart',       file: 'head-shoulders-chart.png' },
  { id: 'ChartPatternsChart',       file: 'chart-patterns-chart.png' },
  { id: 'TradeEntryChart',          file: 'trade-entry-chart.png' },
  { id: 'SupportResistanceChart',   file: 'support-resistance-chart.png' },
  { id: 'MovingAveragesChart',      file: 'moving-averages-chart.png' },
  { id: 'RSIMACDChart',             file: 'rsi-macd-chart.png' },
  { id: 'FibonacciChart',           file: 'fibonacci-chart.png' },
  { id: 'PriceActionChart',         file: 'price-action-chart.png' },
  { id: 'BollingerBandsChart',      file: 'bollinger-bands-chart.png' },
  { id: 'BreakoutChart',            file: 'breakout-chart.png' },
  { id: 'WhatIsForex',              file: 'what-is-forex.png' },
  { id: 'CurrencyPairs',            file: 'currency-pairs.png' },
  { id: 'PipsAndLots',              file: 'pips-and-lots.png' },
  { id: 'BidAskSpread',             file: 'bid-ask-spread.png' },
  { id: 'LeverageExplained',        file: 'leverage-explained.png' },
  { id: 'BullBearMarket',           file: 'bull-bear-market.png' },
  { id: 'RiskRewardVisual',         file: 'risk-reward-visual.png' },
  { id: 'TradingSessionsMap',       file: 'trading-sessions.png' },
  { id: 'TraderMindset',            file: 'trader-mindset.png' },
  { id: 'StopLossVisual',           file: 'stop-loss-visual.png' },
]

// CLI: --id=SomeName to render a single still
const args = Object.fromEntries(process.argv.slice(2).map(a => a.replace(/^--/, '').split('=')))
const targets = args.id ? STILLS.filter(s => s.id === args.id) : STILLS

if (targets.length === 0) {
  console.error(`Unknown id "${args.id}". Valid ids: ${STILLS.map(s => s.id).join(', ')}`)
  process.exit(1)
}

async function main() {
  const outDir = path.join(root, 'public', 'images', 'lessons')
  await fs.mkdir(outDir, { recursive: true })

  console.log('\n🎨  Bundling Remotion project…')
  const bundleLocation = await bundle({
    entryPoint: path.join(root, 'remotion', 'index.ts'),
    webpackOverride: (config) => config,
  })
  console.log('✓  Bundle ready\n')

  let ok = 0, failed = 0

  for (const still of targets) {
    const output = path.join(outDir, still.file)
    process.stdout.write(`  Rendering ${still.id}… `)

    try {
      const composition = await selectComposition({
        serveUrl: bundleLocation,
        id: still.id,
        inputProps: {},
      })

      await renderStill({
        composition,
        serveUrl: bundleLocation,
        output,
        inputProps: {},
        imageFormat: 'png',
        scale: 1,
      })

      console.log(`✓  public/images/lessons/${still.file}`)
      ok++
    } catch (err) {
      console.log(`✗  ERROR: ${err.message}`)
      failed++
    }
  }

  // Write / update the image map (only rendered stills)
  const mapEntries = STILLS.map(s =>
    `  "${s.id}": "/images/lessons/${s.file}"`
  ).join(',\n')

  await fs.writeFile(
    path.join(root, 'lib', 'lessonImageMap.ts'),
    `// Auto-generated by scripts/render-stills.mjs — do not edit manually\n` +
    `export const LESSON_IMAGE_MAP: Record<string, string> = {\n${mapEntries}\n};\n`
  )

  console.log(`\n${'─'.repeat(52)}`)
  console.log(`✅  Rendered : ${ok}`)
  if (failed) console.log(`✗   Failed  : ${failed}`)
  console.log(`📄  Image map written to lib/lessonImageMap.ts`)
  console.log('')
}

main().catch(err => { console.error(err); process.exit(1) })
